version: '3.1'

services:

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      app_net:
        ipv4_address: 172.1.0.99

  db1:
    image: registry.cn-hangzhou.aliyuncs.com/catshop/pxc
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == host-db1
    networks:
      app_net:
        ipv4_address: 172.1.0.100
    ports:
      - "3381:3306"
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123
      CLUSTER_NAME: mycluster
      CLUSTER_ADDRESS: db1,db2
      XTRABACKUP_PASSWORD: 123
      NODE_NAME: pxc1
      NODE_ADDRESS: db1


  db2:
    image: registry.cn-hangzhou.aliyuncs.com/catshop/pxc
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == host-db2
    networks:
      app_net:
        ipv4_address: 172.1.0.101
    depends_on:
      - db1
    ports:
      - "3382:3306"
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123
      CLUSTER_NAME: mycluster
      CLUSTER_ADDRESS: db1,db2
      XTRABACKUP_PASSWORD: 123
      NODE_NAME: pxc2
      NODE_ADDRESS: db2

volumes:
  db_data:

networks:
  app_net:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.1.0.0/16